// This file handles service worker registration and update detection

import { toast } from "react-toastify";

export function register() {
  if ("serviceWorker" in navigator) {
    window.addEventListener("load", () => {
      const swUrl = "/sw.js"; // Generated by vite-plugin-pwa

      navigator.serviceWorker
        .register(swUrl)
        .then((registration) => {
          registration.onupdatefound = () => {
            const installingWorker = registration.installing;
            if (installingWorker == null) return;

            installingWorker.onstatechange = () => {
              if (installingWorker.state === "installed") {
                if (navigator.serviceWorker.controller) {
                  // A new version is available
                  console.log("New content is available; please refresh.");
                  toast.info(
                    "A new version is available. Please refresh the page.",
                  );
                } else {
                  // Content is cached for offline use
                  console.log("Content is cached for offline use.");
                }
              }
            };
          };
        })
        .catch((error) => {
          console.error("Error during service worker registration:", error);
        });
    });
  }
}
